### ISSUE TITLE
Duplicate tag "neogit_c" when updating with lazy

### ISSUE THREAD

**Issue by fnune** [CKolkey/neogit#48]
### Description

```
    ● neogit 28.74ms   Neogit
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:79: Vim:E154: Duplicate tag "neogit_c" in file /home/fausto/.local/share/nvim/lazy/neogit/doc//neogit.txt
```

![image](https://github.com/CKolkey/neogit/assets/16181067/6b708d4a-7f09-4304-891e-9faf7410d569)

Getting this when running `:Lazy update`.

### Neovim version

-

### Operating system and version

-

### Steps to reproduce

-

### Actual behavior

-

### Minimal config

```Lua
-
```

**Comment by CKolkey** [comment]
Arg, wish I had seen this sooner! I merged everything and some other people made an issue. But yes, this was a problem. Thanks for the keen eye ;)
